[mypy]
python_version = 3.10
ignore_missing_imports = True
exclude = (?x)(
    ^venv/
    | ^\.venv/
    | ^env/
    | ^\.git/
    | ^__pycache__/
    | ^site-packages/
    | ^\.tox/
    | ^build/
    | ^dist/
  )

[mypy-pytest.*]
ignore_missing_imports = True

[mypy-_pytest.*]
ignore_missing_imports = True
